- name: Create lambda function
  lambda:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    name: "Hello-World"
    state: present
    zip_file: "lambda_test.zip"
    runtime: 'nodejs8.10'
    role: "lambda_basic_execution_1"
    handler: "lambda_test.handler"
    region: "us-west-2"