- name: Shutdown EC2 instance
  ec2:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    instance_ids: "{{instance_id}}"
    state: stopped
    region: "{{ec2_region}}"