- name: Transfer lambda function to EC2 instance
  copy:
    src: lambda_test.zip
    dest: /usr/local/lambda_test.zip

- name: Upload Lambda Function to S3
  aws_s3:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    bucket: ansible-test-bucket-1216
    object: lambda_test.zip
    src: /usr/local/lambda_test.zip
    mode: put
    region: "{{ec2_region}}"