- name: Download Resume from AWS S3
  aws_s3:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    bucket: ansible-test-bucket-1216
    object: resume.pdf
    dest: /usr/local/resume.pdf
    mode: get
    region: "{{ec2_region}}"